import type { CategoryDefinition, ProcessingBoundary, ToolCategory, ToolAvailability, ToolDefinition } from "./types";

export const categoryMeta: Record<ToolCategory, CategoryDefinition> = {
  image: {
    label: "Image",
    number: "01",
    description: "Make everyday image fixes without opening a heavy editor.",
    visualFormat: "PNG",
    visualName: "photo.png",
    visualSize: "3.8 MB",
    groups: [
      { key: "optimize", label: "Optimize", description: "Reduce image encoding size or improve apparent resolution while keeping the source safe.", toolSlugs: ["compress-image", "upscale-image"] },
      { key: "resize-crop", label: "Resize & crop", description: "Change pixel dimensions or frame an image to a useful ratio.", toolSlugs: ["resize-image", "crop-image"] },
      { key: "format-conversion", label: "Format conversion", description: "Move between supported JPG, PNG, WebP, and HEIC/HEIF image formats.", toolSlugs: ["png-to-jpg", "jpg-to-png", "jpg-to-webp", "png-to-webp", "webp-to-jpg", "webp-to-png", "heic-to-jpg"] },
    ],
    content: {
      heading: "Practical fixes for everyday raster images.",
      body: "Resize, compress, crop, upscale, or change the format of supported raster images without opening a full editor.",
      formats: "JPG/JPEG, PNG, WebP, and supported HEIC/HEIF input for HEIC to JPG.",
      intents: "Reduce file size, change dimensions, upscale a small image, crop to a useful frame, create a transparent cutout, or make an image compatible with another app or service.",
      processing: "Released image routes run in the browser and keep selected files on this device.",
    },
  },
  pdf: {
    label: "PDF & Document",
    number: "02",
    description: "Organize, convert, annotate, extract, and clean useful PDF files.",
    visualFormat: "PDF",
    visualName: "report.pdf",
    visualSize: "12 pages",
    groups: [
      { key: "combine-organize", label: "Organize", description: "Join documents, extract ranges, or change page order and membership.", toolSlugs: ["merge-pdf", "split-pdf", "organize-pdf", "rotate-pdf"] },
      { key: "convert", label: "Convert", description: "Create PDFs from images, render PDF pages, or package plain text.", toolSlugs: ["jpg-to-pdf", "png-to-pdf", "webp-to-pdf", "pdf-to-jpg", "pdf-to-png", "pdf-to-webp", "txt-to-pdf"] },
      { key: "edit-pages", label: "Edit & overlay", description: "Add page numbers, headers, footers, watermarks, or a focused crop box.", toolSlugs: ["watermark-pdf", "add-page-numbers", "header-footer-pdf", "crop-pdf"] },
      { key: "extract", label: "Extract & inspect", description: "Export text, simple HTML, embedded raster images, or reported metadata.", toolSlugs: ["pdf-to-text", "pdf-to-html", "extract-images-from-pdf", "pdf-metadata-viewer"] },
      { key: "clean", label: "Clean & advanced", description: "Remove supported document metadata or flatten interactive form fields.", toolSlugs: ["clean-pdf-metadata", "flatten-pdf", "compress-pdf"] },
    ],
    content: {
      heading: "Page and document workflows in one place.",
      body: "Work with page order, conversions, overlays, extraction, metadata, form flattening, and disclosed PDF compression.",
      formats: "PDF, JPG/JPEG, PNG, WebP, and UTF-8 TXT depending on the selected workflow.",
      intents: "Combine, split, reorder, duplicate, reverse, rotate, number, crop, watermark, extract, inspect, flatten, or convert PDF content.",
      processing: "New browser PDF tools parse or render files on this device. Compress PDF remains the only PDF route using the disclosed temporary native server job.",
    },
  },
  word: {
    label: "Word & Document",
    number: "03",
    description: "Convert, organize, compress, and clean useful Word document formats.",
    visualFormat: "DOCX",
    visualName: "brief.docx",
    visualSize: "3 pages",
    groups: [
      { key: "convert", label: "Convert", description: "Move readable content between DOCX, PDF, HTML, and plain text.", toolSlugs: ["docx-to-pdf", "pdf-to-docx", "docx-to-txt", "txt-to-docx", "docx-to-html", "html-to-docx"] },
      { key: "organize", label: "Organize", description: "Combine compatible DOCX files or extract their embedded images.", toolSlugs: ["merge-docx", "extract-images-from-docx"] },
      { key: "clean", label: "Optimize & clean", description: "Reduce supported embedded JPEG media or remove supported document properties.", toolSlugs: ["compress-docx", "docx-metadata-cleaner"] },
    ],
    content: {
      heading: "Useful Word conversions without a desktop install.",
      body: "Convert readable documents, create editable DOCX files from text or HTML, combine compatible DOCX files, extract embedded images, reduce supported media, and clean supported properties.",
      formats: "DOCX, PDF, TXT, and HTML input; PDF, TXT, HTML, DOCX, image, or ZIP output depending on the selected workflow.",
      intents: "Create a readable PDF, extract text, make an editable DOCX, publish semantic HTML, combine documents, extract media, reduce JPEG payloads, or remove supported properties.",
      processing: "Text, HTML, DOCX organization, compression, and metadata routes run locally in the browser. DOCX to PDF and PDF to DOCX use a disclosed temporary native document job for better layout and structure fidelity.",
    },
  },
  audio: {
    label: "Audio",
    number: "04",
    description: "Trim, merge, and convert audio with clear controls and useful defaults.",
    visualFormat: "MP3",
    visualName: "interview.mp3",
    visualSize: "8.4 MB",
    groups: [
      { key: "edit", label: "Edit", description: "Trim a time range or join multiple tracks into one.", toolSlugs: ["trim-audio", "merge-audio"] },
      { key: "convert", label: "Convert", description: "Move between the verified common audio formats.", toolSlugs: ["audio-converter"] },
      { key: "compress", label: "Compress", description: "Reduce bitrate and file size with understandable presets.", toolSlugs: ["compress-audio"] },
    ],
    content: {
      heading: "Clear controls for common audio edits.",
      body: "Trim a section, join tracks, change a supported format, or reduce bitrate with understandable quality presets.",
      formats: "MP3, WAV, M4A/AAC, FLAC, and OGG/Vorbis within the verified audio matrix.",
      intents: "Cut a clip, make one continuous track, export another audio format, or make a file smaller.",
      processing: "Audio routes use the approved browser runtime and keep selected files on the device.",
    },
  },
  video: {
    label: "Video",
    number: "05",
    description: "Extract audio and remux verified MOV files without changing the original video streams.",
    visualFormat: "MP4",
    visualName: "clip.mp4",
    visualSize: "84 MB",
    groups: [
      { key: "edit", label: "Edit", description: "Keep a keyframe-aligned section of verified video.", toolSlugs: ["trim-video"] },
      { key: "convert", label: "Convert", description: "Extract audio or remux supported MP4 and MOV containers.", toolSlugs: ["video-to-mp3", "mov-to-mp4", "video-converter"] },
      { key: "compress", label: "Compress", description: "Use the disclosed temporary workflow to create a smaller WebM result.", toolSlugs: ["compress-video"] },
    ],
    content: {
      heading: "Focused video workflows for verified files.",
      body: "Trim supported H.264 video, extract MP3 audio, remux MOV and MP4 containers, or use the disclosed compression route.",
      formats: "MP4 and QuickTime MOV with the route-specific H.264/AAC support matrix.",
      intents: "Cut a keyframe-aligned clip, get audio from a video, make MOV compatible with MP4, or change a supported container.",
      processing: "Trim, extraction, and remux routes run locally; Compress Video uses a disclosed temporary server job and automatic deletion.",
    },
  },
};

export const tools: ToolDefinition[] = [
  {
    id: "IMG-01",
    slug: "compress-image",
    category: "image",
    title: "Compress Image",
    description: "Reduce image size while keeping the dimensions you need.",
    processor: "image",
    input: { formats: ["JPG", "PNG", "WebP"], extensions: ["jpg", "jpeg", "png", "webp"], mimes: ["image/jpeg", "image/png", "image/webp"] },
    output: { formats: ["JPG", "PNG", "WebP"], suffix: "optimized" },
    batch: true,
    action: "Compress image",
    keywords: ["shrink", "optimize", "smaller", "quality"],
    featured: true,
  },
  {
    id: "IMG-02",
    slug: "resize-image",
    category: "image",
    title: "Resize Image",
    description: "Scale images by percentage while keeping the original safe.",
    processor: "image",
    input: { formats: ["JPG", "PNG", "WebP"], extensions: ["jpg", "jpeg", "png", "webp"], mimes: ["image/jpeg", "image/png", "image/webp"] },
    output: { formats: ["JPG", "PNG", "WebP"], suffix: "resized" },
    batch: true,
    action: "Resize image",
    keywords: ["dimensions", "pixels", "scale", "smaller", "larger"],
    featured: true,
  },
  {
    id: "IMG-03",
    slug: "crop-image",
    category: "image",
    title: "Crop Image",
    description: "Select a freeform or common-ratio crop area, preview it, and export a clean raster image.",
    processor: "image",
    input: { formats: ["JPG", "PNG", "WebP"], extensions: ["jpg", "jpeg", "png", "webp"], mimes: ["image/jpeg", "image/png", "image/webp"] },
    output: { formats: ["JPG", "PNG", "WebP"], suffix: "cropped" },
    batch: false,
    action: "Crop image",
    keywords: ["trim", "frame", "aspect ratio", "square"],
    featured: false,
  },
  {
    id: "IMG-13",
    slug: "upscale-image",
    category: "image",
    title: "Image Upscaler",
    description: "Enhance one JPG, PNG, or WebP image with a lazy-loaded 3× super-resolution model.",
    processor: "image-upscaler",
    input: { formats: ["JPG", "PNG", "WebP"], extensions: ["jpg", "jpeg", "png", "webp"], mimes: ["image/jpeg", "image/png", "image/webp"] },
    output: { formats: ["PNG"], suffix: "upscaled" },
    batch: false,
    action: "Upscale image",
    keywords: ["enlarge", "resolution", "3x", "super-resolution", "enhance"],
    searchTerms: ["increase image resolution", "enlarge image", "upscale photo"],
    metaDescription: "Enhance a JPG, PNG, or WebP image with a local 3× super-resolution model and download a PNG result. No image API is used.",
    seoCopy: "Run one JPG, PNG, or WebP image through a locally loaded ONNX super-resolution model and download a 3× PNG result. The model improves luminance detail, while color and transparency use browser-safe resizing; it cannot recreate guaranteed original detail.",
    faqs: [
      { question: "Which image formats are accepted?", answer: "Image Upscaler accepts readable JPG, JPEG, PNG, and WebP files." },
      { question: "Which scale is available?", answer: "The route currently produces a fixed 3× PNG result because the selected model is trained for 3× output." },
      { question: "Does the model recover guaranteed original detail?", answer: "No. Super-resolution estimates plausible higher-resolution detail from the source; it cannot guarantee recovery of information that was never captured." },
      { question: "Where is the image processed?", answer: "The image and model inference run in the browser. The model asset may be downloaded on first use, but the selected image is not uploaded to an image API or stored by DoMyFile." },
    ],
    featured: true,
  },
  {
    id: "IMG-12",
    slug: "remove-background",
    category: "image",
    title: "Remove Background",
    description: "Held native background-removal route; public processing is currently disabled.",
    processor: "background-removal",
    processingBoundary: "server",
    input: { formats: ["JPG", "PNG", "WebP"], extensions: ["jpg", "jpeg", "png", "webp"], mimes: ["image/jpeg", "image/png", "image/webp"] },
    output: { formats: ["Transparent PNG"], suffix: "no-background" },
    batch: false,
    action: "Remove background",
    keywords: ["cutout", "transparent", "foreground", "subject", "background remover"],
    searchTerms: ["transparent background", "image background remover", "make image background transparent"],
    metaDescription: "Remove the background from a JPG, PNG, or WebP image with a pinned native BiRefNet-lite model and download a transparent PNG.",
    seoCopy: "Create a transparent PNG cutout from one JPG, PNG, or WebP image through a pinned BiRefNet-lite ONNX model in the temporary native processing path. The image is deleted automatically after the short-lived job; no paid image API is used.",
    faqs: [
      { question: "Which image formats are accepted?", answer: "Remove Background accepts JPG, JPEG, PNG, and WebP files with readable image signatures." },
      { question: "What format will I download?", answer: "The result is always a PNG with transparent pixels around the detected foreground." },
      { question: "Does the image leave my device?", answer: "Yes. This quality-focused route uses an approved temporary native container. The source is kept in private temporary storage, deleted after success or expiry, and is not sent to a paid third-party image API." },
    ],
    serverDisclosure: "This image is temporarily uploaded to an isolated native segmentation container and deleted automatically after the job completes, fails, is cancelled, or expires.",
    featured: false,
    availability: "deferred",
    statusReason: "Remove Background is disabled while its native container release gates are completed. No files are accepted or uploaded on this route.",
  },
  {
    id: "IMG-05",
    slug: "png-to-jpg",
    category: "image",
    title: "PNG to JPG",
    description: "Convert PNG images to JPG and choose a background for transparent pixels.",
    processor: "image",
    input: { formats: ["PNG"], extensions: ["png"], mimes: ["image/png"] },
    output: { formats: ["JPG"], suffix: "jpg" },
    batch: true,
    action: "Convert to JPG",
    keywords: ["transparent", "background", "jpeg", "convert"],
    searchTerms: ["png to jpeg", "png image to jpg"],
    metaDescription: "Convert PNG images to JPG with a chosen background for transparent pixels. Process files locally with DoMyFile.",
    seoCopy: "Convert PNG images to fixed-output JPG files in your browser. Transparent pixels use a white background by default, and you can choose another color before processing.",
    faqs: [
      { question: "What does PNG to JPG accept?", answer: "This route accepts PNG images only and rejects other image formats before processing." },
      { question: "What happens to transparent pixels?", answer: "JPG does not support transparency, so transparent pixels use the selected background color. White is the default." },
      { question: "What will I download?", answer: "Every successful result is a JPG file with the original image dimensions." },
    ],
    featured: true,
  },
  {
    id: "IMG-06",
    slug: "jpg-to-png",
    category: "image",
    title: "JPG to PNG",
    description: "Convert JPG images to PNG while preserving their original dimensions.",
    processor: "image",
    input: { formats: ["JPG"], extensions: ["jpg", "jpeg"], mimes: ["image/jpeg"] },
    output: { formats: ["PNG"], suffix: "png" },
    batch: true,
    action: "Convert to PNG",
    keywords: ["convert", "jpeg", "lossless", "image"],
    searchTerms: ["jpg to jpeg", "jpeg to png", "jpg image to png"],
    metaDescription: "Convert JPG images to PNG while keeping their dimensions. DoMyFile processes JPG files locally in your browser.",
    seoCopy: "Convert JPG images to fixed-output PNG files without changing their decoded dimensions. Select one or more JPG files and download the PNG results locally.",
    faqs: [
      { question: "What does JPG to PNG accept?", answer: "This route accepts JPG and JPEG images only. PNG, WebP, and other files are rejected before conversion." },
      { question: "Will the dimensions change?", answer: "No. The shared Image Engine preserves the decoded width and height for JPG to PNG conversion." },
      { question: "What will I download?", answer: "Every successful result is a PNG file." },
    ],
    featured: false,
  },
  {
    id: "IMG-07",
    slug: "jpg-to-webp",
    category: "image",
    title: "JPG to WebP",
    description: "Convert JPG images to compact WebP files for modern websites and apps.",
    processor: "image",
    input: { formats: ["JPG"], extensions: ["jpg", "jpeg"], mimes: ["image/jpeg"] },
    output: { formats: ["WebP"], suffix: "webp" },
    batch: true,
    action: "Convert to WebP",
    keywords: ["jpeg", "modern", "website", "smaller", "image"],
    searchTerms: ["jpg image to webp", "jpeg to webp"],
    metaDescription: "Convert JPG images to WebP for modern websites and apps. Choose files and create WebP results locally with DoMyFile.",
    seoCopy: "Convert JPG images to fixed-output WebP files with the shared Image Engine. The conversion runs locally and keeps the original dimensions.",
    faqs: [
      { question: "What does JPG to WebP accept?", answer: "This route accepts JPG and JPEG images only." },
      { question: "What format is the result?", answer: "Every successful result is WebP. There is no output-format selector on this focused route." },
      { question: "Can I convert multiple JPG files?", answer: "Yes. JPG to WebP keeps the existing batch workflow, so you can select multiple JPG files in one job." },
    ],
    featured: true,
  },
  {
    id: "IMG-09",
    slug: "png-to-webp",
    category: "image",
    title: "PNG to WebP",
    description: "Convert PNG images to WebP for a smaller, web-ready image.",
    processor: "image",
    input: { formats: ["PNG"], extensions: ["png"], mimes: ["image/png"] },
    output: { formats: ["WebP"], suffix: "webp" },
    batch: true,
    action: "Convert to WebP",
    keywords: ["modern", "website", "smaller", "image", "transparent"],
    searchTerms: ["png image to webp"],
    metaDescription: "Convert PNG images to WebP for web-ready files with smaller sizes. DoMyFile keeps this batch workflow in your browser.",
    seoCopy: "Convert PNG images to fixed-output WebP files while keeping the decoded dimensions. Select one or more PNG images and download the web-ready results.",
    faqs: [
      { question: "What does PNG to WebP accept?", answer: "This route accepts PNG images only." },
      { question: "What format is the result?", answer: "Every successful result is WebP. The output format is fixed to keep the workflow focused." },
      { question: "Does the route support batches?", answer: "Yes. You can select multiple PNG files and receive one WebP result for each successful input." },
    ],
    featured: false,
  },
  {
    id: "IMG-10",
    slug: "webp-to-jpg",
    category: "image",
    title: "WebP to JPG",
    description: "Convert WebP images to broadly compatible JPG files.",
    processor: "image",
    input: { formats: ["WebP"], extensions: ["webp"], mimes: ["image/webp"] },
    output: { formats: ["JPG"], suffix: "jpg" },
    batch: true,
    action: "Convert to JPG",
    keywords: ["compatibility", "jpeg", "image", "convert"],
    searchTerms: ["webp image to jpg", "webp to jpeg"],
    metaDescription: "Convert WebP images to compatible JPG files with DoMyFile. Select WebP images and process them locally in your browser.",
    seoCopy: "Convert WebP images to fixed-output JPG files for apps and services that need broad JPEG compatibility. The shared Image Engine processes each file locally.",
    faqs: [
      { question: "What does WebP to JPG accept?", answer: "This route accepts WebP images only." },
      { question: "What happens to transparency?", answer: "JPG does not support transparency, so transparent pixels use a white background." },
      { question: "Can I convert multiple WebP files?", answer: "Yes. Batch conversion is supported, with one JPG result per successful WebP input." },
    ],
    featured: false,
  },
  {
    id: "IMG-11",
    slug: "webp-to-png",
    category: "image",
    title: "WebP to PNG",
    description: "Convert WebP images to PNG while keeping their original dimensions.",
    processor: "image",
    input: { formats: ["WebP"], extensions: ["webp"], mimes: ["image/webp"] },
    output: { formats: ["PNG"], suffix: "png" },
    batch: true,
    action: "Convert to PNG",
    keywords: ["lossless", "transparent", "image", "convert"],
    searchTerms: ["webp image to png"],
    metaDescription: "Convert WebP images to PNG while preserving dimensions. DoMyFile processes WebP files locally and fixes the output to PNG.",
    seoCopy: "Convert WebP images to fixed-output PNG files without changing their decoded dimensions. Select one or more WebP files for a local batch conversion.",
    faqs: [
      { question: "What does WebP to PNG accept?", answer: "This route accepts WebP images only." },
      { question: "Will the dimensions change?", answer: "No. The shared Image Engine preserves the decoded width and height for WebP to PNG conversion." },
      { question: "What format is the result?", answer: "Every successful result is PNG, with no output-format dropdown." },
    ],
    featured: false,
  },
  {
    id: "IMG-08",
    slug: "heic-to-jpg",
    category: "image",
    title: "HEIC to JPG",
    description: "Prepare supported HEIC or HEIF images for broader compatibility.",
    processor: "image",
    input: { formats: ["HEIC", "HEIF"], extensions: ["heic", "heif"], mimes: ["image/heic", "image/heif"] },
    output: { formats: ["JPG"], suffix: "jpg" },
    batch: true,
    action: "Convert to JPG",
    keywords: ["iphone", "apple", "photo", "compatibility"],
    featured: false,
  },
  {
    id: "PDF-01",
    slug: "compress-pdf",
    category: "pdf",
    title: "Compress PDF",
    description: "Reduce PDF size while preserving selectable text, vector content, and page structure where possible.",
    processor: "server",
    processingBoundary: "server",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "compressed" },
    batch: false,
    action: "Compress PDF",
    keywords: ["shrink", "optimize", "document", "smaller"],
    featured: false,
    serverDisclosure: "This file is temporarily uploaded only to create the compressed result, then the temporary data is deleted automatically when the job completes or expires.",
  },
  {
    id: "PDF-02",
    slug: "merge-pdf",
    category: "pdf",
    title: "Merge PDF",
    description: "Combine two or more PDFs and keep their page order under control.",
    processor: "pdf",
    input: { formats: ["PDF", "2+ files"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "merged" },
    batch: true,
    minimumFiles: 2,
    action: "Merge PDFs",
    keywords: ["combine", "join", "documents", "pages"],
    featured: true,
  },
  {
    id: "PDF-03",
    slug: "split-pdf",
    category: "pdf",
    title: "Split PDF",
    description: "Turn selected pages or ranges into separate PDF files.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "split" },
    batch: false,
    action: "Split PDF",
    keywords: ["separate", "pages", "extract", "range"],
    featured: false,
  },
  {
    id: "PDF-09",
    slug: "jpg-to-pdf",
    category: "pdf",
    title: "JPG to PDF",
    description: "Turn one or more JPG images into a clean PDF with page controls.",
    processor: "pdf",
    input: { formats: ["JPG"], extensions: ["jpg", "jpeg"], mimes: ["image/jpeg"] },
    output: { formats: ["PDF"], suffix: "pdf" },
    batch: true,
    action: "Convert to PDF",
    keywords: ["photo", "document", "pages", "convert", "create"],
    searchTerms: ["jpg image to pdf", "jpeg to pdf", "photo jpg to pdf"],
    metaDescription: "Convert one or more JPG images to PDF with page size, orientation, and order controls. Process files locally with DoMyFile.",
    seoCopy: "Turn JPG images into a fixed-output PDF directly in your browser. Add multiple JPG files, arrange their page order, and choose a page size or orientation.",
    faqs: [
      { question: "What does JPG to PDF accept?", answer: "This route accepts JPG and JPEG images only." },
      { question: "Can I add multiple JPG images?", answer: "Yes. Batch support is preserved, and each selected JPG becomes one PDF page in the chosen order." },
      { question: "What format is the result?", answer: "Every successful job creates a PDF. Page size and orientation are configurable, but the output format is fixed." },
    ],
    featured: true,
  },
  {
    id: "PDF-10",
    slug: "png-to-pdf",
    category: "pdf",
    title: "PNG to PDF",
    description: "Turn one or more PNG images into a clean PDF with page controls.",
    processor: "pdf",
    input: { formats: ["PNG"], extensions: ["png"], mimes: ["image/png"] },
    output: { formats: ["PDF"], suffix: "pdf" },
    batch: true,
    action: "Convert to PDF",
    keywords: ["image", "document", "pages", "convert", "create"],
    searchTerms: ["png image to pdf"],
    metaDescription: "Convert one or more PNG images to PDF with page size, orientation, and order controls. DoMyFile processes PNG files locally.",
    seoCopy: "Turn PNG images into a fixed-output PDF in your browser. Select one or more PNG files, review their page order, and use the available page controls.",
    faqs: [
      { question: "What does PNG to PDF accept?", answer: "This route accepts PNG images only." },
      { question: "Can I convert a batch of PNG files?", answer: "Yes. Each selected PNG becomes one PDF page, and you can reorder the pages before creating the PDF." },
      { question: "What format is the result?", answer: "Every successful job creates a PDF. The output format is fixed to PDF." },
    ],
    featured: false,
  },
  {
    id: "PDF-11",
    slug: "webp-to-pdf",
    category: "pdf",
    title: "WebP to PDF",
    description: "Turn one or more WebP images into a clean PDF with page controls.",
    processor: "pdf",
    input: { formats: ["WebP"], extensions: ["webp"], mimes: ["image/webp"] },
    output: { formats: ["PDF"], suffix: "pdf" },
    batch: true,
    action: "Convert to PDF",
    keywords: ["image", "document", "pages", "convert", "create", "web"],
    searchTerms: ["webp image to pdf"],
    metaDescription: "Convert one or more WebP images to PDF with page size, orientation, and order controls. DoMyFile keeps the workflow local.",
    seoCopy: "Turn WebP images into a fixed-output PDF in your browser. Add multiple WebP files, review the page order, and choose the page layout before download.",
    faqs: [
      { question: "What does WebP to PDF accept?", answer: "This route accepts WebP images only." },
      { question: "Can I add multiple WebP images?", answer: "Yes. Batch support is preserved, with one PDF page for each successful WebP input." },
      { question: "What format is the result?", answer: "Every successful job creates a PDF. Page layout is configurable, but the output format is fixed." },
    ],
    featured: false,
  },
  {
    id: "PDF-05",
    slug: "pdf-to-jpg",
    category: "pdf",
    title: "PDF to JPG",
    description: "Export selected PDF pages as broadly compatible JPG images.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["JPG"], suffix: "jpg" },
    batch: false,
    action: "Convert to JPG",
    keywords: ["render", "pages", "image", "export"],
    featured: false,
  },
  {
    id: "PDF-06",
    slug: "organize-pdf",
    category: "pdf",
    title: "Organize PDF",
    description: "Reorder, duplicate, or remove pages in one focused workspace.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "organized" },
    batch: false,
    action: "Organize PDF",
    keywords: ["reorder", "duplicate", "delete", "pages"],
    featured: false,
  },
  {
    id: "PDF-07",
    slug: "rotate-pdf",
    category: "pdf",
    title: "Rotate PDF",
    description: "Rotate selected pages or the whole document by right angles.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "rotated" },
    batch: false,
    action: "Rotate PDF",
    keywords: ["turn", "landscape", "portrait", "pages"],
    featured: false,
  },
  {
    id: "PDF-08",
    slug: "watermark-pdf",
    category: "pdf",
    title: "Watermark PDF",
    description: "Add a visible text or image watermark with simple placement controls.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "watermarked" },
    batch: false,
    action: "Watermark PDF",
    keywords: ["stamp", "protect", "label", "overlay"],
    featured: false,
  },
  {
    id: "PDF-12",
    slug: "pdf-to-png",
    category: "pdf",
    title: "PDF to PNG",
    description: "Render selected PDF pages as PNG images with a chosen page scale.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PNG"], suffix: "png" },
    batch: false,
    action: "Convert to PNG",
    keywords: ["render", "pages", "image", "export", "png"],
    searchTerms: ["convert pdf to png", "save pdf pages as png"],
    featured: false,
  },
  {
    id: "PDF-13",
    slug: "pdf-to-webp",
    category: "pdf",
    title: "PDF to WebP",
    description: "Render selected PDF pages as WebP images with scale and quality controls.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["WebP"], suffix: "webp" },
    batch: false,
    action: "Convert to WebP",
    keywords: ["render", "pages", "image", "export", "webp"],
    searchTerms: ["convert pdf to webp", "save pdf pages as webp"],
    featured: false,
  },
  {
    id: "PDF-14",
    slug: "extract-images-from-pdf",
    category: "pdf",
    title: "Extract Images from PDF",
    description: "Extract decodable embedded raster images from a PDF as individual PNG or WebP files.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PNG", "WebP", "ZIP"], suffix: "images" },
    batch: false,
    action: "Extract images",
    keywords: ["extract", "embedded", "images", "media", "pdf"],
    searchTerms: ["extract images from pdf", "save pictures from pdf"],
    featured: false,
  },
  {
    id: "PDF-15",
    slug: "add-page-numbers",
    category: "pdf",
    title: "Add Page Numbers to PDF",
    description: "Add selectable page numbers to chosen PDF pages with a start number and placement.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "numbered" },
    batch: false,
    action: "Add page numbers",
    keywords: ["number", "paginate", "pages", "footer", "pdf"],
    searchTerms: ["add page numbers to pdf", "number pdf pages"],
    featured: false,
  },
  {
    id: "PDF-16",
    slug: "header-footer-pdf",
    category: "pdf",
    title: "Add Header and Footer to PDF",
    description: "Place simple selectable header and footer text on selected PDF pages.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "header-footer" },
    batch: false,
    action: "Add header and footer",
    keywords: ["header", "footer", "text", "overlay", "pdf"],
    searchTerms: ["add header footer to pdf", "pdf header footer"],
    featured: false,
  },
  {
    id: "PDF-17",
    slug: "crop-pdf",
    category: "pdf",
    title: "Crop PDF Pages",
    description: "Apply a consistent visible crop box to every page without rasterizing the document.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "cropped" },
    batch: false,
    action: "Crop PDF pages",
    keywords: ["crop", "trim", "margins", "pages", "pdf"],
    searchTerms: ["crop pdf", "trim pdf pages"],
    featured: false,
  },
  {
    id: "PDF-18",
    slug: "pdf-to-text",
    category: "pdf",
    title: "PDF to Text",
    description: "Extract selectable text from a PDF into a plain UTF-8 TXT file.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["TXT"], suffix: "text" },
    batch: false,
    action: "Extract text",
    keywords: ["extract", "text", "plain text", "copy", "pdf"],
    searchTerms: ["pdf to text", "extract text from pdf"],
    featured: false,
  },
  {
    id: "PDF-19",
    slug: "pdf-to-html",
    category: "pdf",
    title: "PDF to HTML",
    description: "Export selectable PDF text into a simple semantic HTML document organized by page.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["HTML"], suffix: "html" },
    batch: false,
    action: "Convert to HTML",
    keywords: ["convert", "html", "text", "extract", "pdf"],
    searchTerms: ["pdf to html", "convert pdf to web page"],
    featured: false,
  },
  {
    id: "PDF-20",
    slug: "pdf-metadata-viewer",
    category: "pdf",
    title: "PDF Metadata Viewer",
    description: "Inspect metadata reported by the PDF parser and download a JSON summary.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["JSON"], suffix: "metadata" },
    batch: false,
    action: "View PDF metadata",
    keywords: ["metadata", "inspect", "properties", "privacy", "pdf"],
    searchTerms: ["pdf metadata viewer", "view pdf properties"],
    featured: false,
  },
  {
    id: "PDF-21",
    slug: "clean-pdf-metadata",
    category: "pdf",
    title: "Clean PDF Metadata",
    description: "Remove standard document information and the catalog XMP metadata stream from a PDF.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "metadata-cleaned" },
    batch: false,
    action: "Clean PDF metadata",
    keywords: ["remove", "metadata", "privacy", "properties", "pdf"],
    searchTerms: ["remove metadata from pdf", "clean pdf properties"],
    featured: false,
  },
  {
    id: "PDF-22",
    slug: "txt-to-pdf",
    category: "pdf",
    title: "TXT to PDF",
    description: "Turn a UTF-8 plain text file into a selectable PDF with simple page layout controls.",
    processor: "pdf",
    input: { formats: ["TXT"], extensions: ["txt"], mimes: ["text/plain"] },
    output: { formats: ["PDF"], suffix: "pdf" },
    batch: false,
    action: "Convert to PDF",
    keywords: ["text", "document", "convert", "create", "pdf"],
    searchTerms: ["txt to pdf", "convert text file to pdf"],
    featured: false,
  },
  {
    id: "PDF-23",
    slug: "flatten-pdf",
    category: "pdf",
    title: "Flatten PDF Form",
    description: "Flatten supported interactive form fields into page content while keeping the PDF readable.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "flattened" },
    batch: false,
    action: "Flatten PDF",
    keywords: ["flatten", "form", "fields", "annotation", "pdf"],
    searchTerms: ["flatten pdf form", "flatten pdf fields"],
    featured: false,
  },
  {
    id: "DOC-01",
    slug: "docx-to-txt",
    category: "word",
    title: "DOCX to TXT",
    description: "Extract readable paragraph text from a DOCX file as a plain TXT download.",
    processor: "document",
    input: { formats: ["DOCX"], extensions: ["docx"], mimes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
    output: { formats: ["TXT"], suffix: "text" },
    batch: false,
    action: "Extract text",
    keywords: ["extract", "plain text", "word", "document", "copy text"],
    searchTerms: ["word document to text", "convert docx to text", "extract text from docx"],
    metaDescription: "Extract readable text from a DOCX file and download it as TXT. DoMyFile processes the document locally in your browser.",
    seoCopy: "Extract paragraph text from a DOCX file into a plain TXT download. The focused route keeps the formatting-free result useful for search, scripts, notes, and copy-paste workflows.",
    faqs: [
      { question: "What does DOCX to TXT keep?", answer: "It keeps readable paragraph text and removes Word formatting. Headings, lists, and table cell text are represented as plain text where the parser exposes them." },
      { question: "Does it accept old DOC files?", answer: "No. This route accepts modern DOCX files only; legacy .doc files are not parsed." },
      { question: "Where is the conversion performed?", answer: "The DOCX parser loads in your browser and the selected document is not uploaded or stored." },
    ],
    featured: false,
  },
  {
    id: "DOC-02",
    slug: "docx-to-html",
    category: "word",
    title: "DOCX to HTML",
    description: "Convert a DOCX file into a downloadable semantic HTML document.",
    processor: "document",
    input: { formats: ["DOCX"], extensions: ["docx"], mimes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
    output: { formats: ["HTML"], suffix: "html" },
    batch: false,
    action: "Convert to HTML",
    keywords: ["html", "web", "word", "semantic", "publish"],
    searchTerms: ["convert word to html", "docx to html converter", "word document to html"],
    metaDescription: "Convert a DOCX file to a semantic HTML document locally in your browser. Download the resulting .html file with DoMyFile.",
    seoCopy: "Turn a DOCX file into a complete HTML download with semantic headings, paragraphs, lists, and supported inline images. Complex Word layout and styling may need manual cleanup after conversion.",
    faqs: [
      { question: "What does DOCX to HTML output?", answer: "The result is a complete .html file containing the converted document body and semantic HTML where the DOCX structure maps cleanly." },
      { question: "Will the HTML match Word pixel for pixel?", answer: "No. The converter prioritizes readable semantic HTML; complex layout, tracked changes, headers, footers, and some styling may not map exactly." },
      { question: "Can a legacy .doc file be used here?", answer: "No. Only modern DOCX input is supported on this route." },
    ],
    featured: false,
  },
  {
    id: "DOC-03",
    slug: "txt-to-docx",
    category: "word",
    title: "TXT to DOCX",
    description: "Turn a plain TXT file into a simple Word document with one paragraph per line.",
    processor: "document",
    input: { formats: ["TXT"], extensions: ["txt"], mimes: ["text/plain"] },
    output: { formats: ["DOCX"], suffix: "docx" },
    batch: false,
    action: "Create DOCX",
    keywords: ["plain text", "word", "document", "create", "export"],
    searchTerms: ["convert text to word", "txt to word", "create docx from txt"],
    metaDescription: "Turn a plain TXT file into a simple DOCX document with one paragraph per line. Processing stays in your browser with DoMyFile.",
    seoCopy: "Package a non-empty TXT file into a standard DOCX document. Each source line becomes a paragraph, making the result predictable and easy to continue editing in Word-compatible apps.",
    faqs: [
      { question: "How are TXT lines represented in the DOCX?", answer: "Each line becomes one paragraph in the generated DOCX. Blank lines remain blank paragraphs." },
      { question: "Does TXT to DOCX add headings or styling?", answer: "No. This focused route creates plain paragraphs and does not guess headings, lists, fonts, or page layout from raw text." },
      { question: "What input is accepted?", answer: "The route accepts non-empty UTF-8-compatible .txt files and rejects binary-looking content or other extensions." },
    ],
    featured: false,
  },
  {
    id: "DOC-04",
    slug: "docx-to-pdf",
    category: "word",
    title: "DOCX to PDF",
    description: "Convert a DOCX document to PDF with a native document engine for stronger layout fidelity.",
    processor: "server",
    processingBoundary: "server",
    input: { formats: ["DOCX"], extensions: ["docx"], mimes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
    output: { formats: ["PDF"], suffix: "pdf" },
    batch: false,
    action: "Convert to PDF",
    keywords: ["word", "document", "export", "print", "pages"],
    searchTerms: ["convert docx to pdf", "word document to pdf", "word to pdf"],
    metaDescription: "Convert a DOCX document to PDF with a temporary native document job that keeps Word pagination, text, tables, and supported embedded media useful.",
    seoCopy: "Convert one modern DOCX file to PDF through an isolated, temporary LibreOffice Writer job. The native document engine is used for substantially better pagination and layout fidelity than a browser HTML snapshot, but exact Microsoft Word font and feature parity is not guaranteed.",
    faqs: [
      { question: "What does DOCX to PDF preserve?", answer: "The native Writer conversion is intended to preserve document pagination, selectable text, tables, and supported embedded media more faithfully than a browser snapshot." },
      { question: "Is the PDF pixel-perfect compared with Microsoft Word?", answer: "No. Native conversion is substantially closer to Word-style layout, but font availability, unsupported Word features, fields, and exact application rendering can still differ." },
      { question: "Are legacy DOC files accepted?", answer: "No. This route accepts modern DOCX archives only." },
      { question: "Does the file leave my device?", answer: "Yes. This quality-focused route uses a temporary isolated server job; the upload and generated PDF are deleted automatically after the short-lived job." },
    ],
    serverDisclosure: "This DOCX is temporarily uploaded to an isolated native document converter and deleted automatically after the job.",
    featured: false,
  },
  {
    id: "DOC-05",
    slug: "pdf-to-docx",
    category: "word",
    title: "PDF to DOCX",
    description: "Convert a text-based PDF to an editable DOCX with a native PDF import path and no OCR claim.",
    processor: "server",
    processingBoundary: "server",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["DOCX"], suffix: "editable" },
    batch: false,
    action: "Create editable DOCX",
    keywords: ["pdf", "word", "editable", "extract", "text"],
    searchTerms: ["convert pdf to docx", "pdf to word", "make pdf editable"],
    metaDescription: "Convert a text-based PDF to an editable DOCX through a temporary native document job. Scanned PDFs remain unsupported because the route does not run OCR.",
    seoCopy: "Create an editable DOCX from a PDF with selectable text through an isolated LibreOffice PDF-import job. The native importer can retain useful text, page structure, and embedded content where the source permits it; scanned or image-only PDFs are rejected because this route does not run OCR, and exact layout recovery is not guaranteed.",
    faqs: [
      { question: "Does PDF to DOCX run OCR?", answer: "No. The route requires selectable PDF text and does not automatically OCR scanned or image-only pages." },
      { question: "Will the DOCX match the PDF layout exactly?", answer: "No. Native PDF import can retain useful page structure and images, but positioned text, columns, forms, fonts, and complex layouts may require cleanup in Word." },
      { question: "Are password-protected PDFs supported?", answer: "No. Encrypted or password-protected PDFs are rejected with a clear error." },
      { question: "Where is the PDF processed?", answer: "The PDF is temporarily uploaded to an isolated native converter and deleted automatically after the short-lived job; it is not stored as a user file." },
    ],
    serverDisclosure: "This PDF is temporarily uploaded to an isolated native document converter and deleted automatically after the job.",
    featured: false,
  },
  {
    id: "DOC-06",
    slug: "html-to-docx",
    category: "word",
    title: "HTML to DOCX",
    description: "Turn supported HTML headings, text, lists, tables, and links into an editable DOCX.",
    processor: "document",
    input: { formats: ["HTML"], extensions: ["html", "htm"], mimes: ["text/html"] },
    output: { formats: ["DOCX"], suffix: "docx" },
    batch: false,
    action: "Convert to DOCX",
    keywords: ["html", "word", "document", "headings", "tables"],
    searchTerms: ["convert html to docx", "html to word", "web page to docx"],
    metaDescription: "Convert supported HTML files to editable DOCX documents with headings, paragraphs, formatting, lists, tables, and safe links.",
    seoCopy: "Convert one HTML file into a DOCX using a restricted safe subset: headings, paragraphs, bold and italic text, lists, tables, line breaks, and HTTP or mailto links. Scripts, event handlers, active embeds, stylesheets, and images are not executed or imported.",
    faqs: [
      { question: "Which HTML elements are supported?", answer: "The converter supports headings, paragraphs, bold/italic/underlined text, lists, tables, line breaks, and safe HTTP or mailto links." },
      { question: "Are scripts or event handlers executed?", answer: "No. The uploaded HTML is parsed through a whitelist; scripts, event handlers, active embeds, stylesheets, and unsafe links are ignored." },
      { question: "Does it preserve CSS layout or images?", answer: "No. Complex CSS layout and images are outside the supported subset, so the result focuses on editable document content." },
      { question: "Where is HTML processed?", answer: "The HTML is sanitized and converted to DOCX locally in the browser." },
    ],
    featured: false,
  },
  {
    id: "DOC-07",
    slug: "merge-docx",
    category: "word",
    title: "Merge DOCX",
    description: "Combine two or more compatible DOCX files with reorderable input and preserved embedded images.",
    processor: "document",
    input: { formats: ["DOCX", "2+ files"], extensions: ["docx"], mimes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
    output: { formats: ["DOCX"], suffix: "merged" },
    batch: true,
    minimumFiles: 2,
    action: "Merge DOCX files",
    keywords: ["combine", "join", "word", "documents", "merge"],
    searchTerms: ["merge docx files", "combine word documents", "join docx"],
    metaDescription: "Merge two or more DOCX files into one editable DOCX locally. Reorder inputs and preserve supported paragraphs, lists, tables, styles, numbering, hyperlinks, and embedded images.",
    seoCopy: "Combine compatible modern DOCX archives into one editable document. Reorder the files before processing; the browser merges document XML, styles, numbering, hyperlinks, and embedded images, inserting a page break between source documents.",
    faqs: [
      { question: "How many DOCX files can I merge?", answer: "The route requires at least two DOCX files. Add and reorder the files before processing." },
      { question: "Are embedded images preserved?", answer: "Supported embedded raster images are copied into the merged DOCX with remapped relationships." },
      { question: "What happens between source documents?", answer: "A page break is inserted so the next source document starts on a new page." },
      { question: "Are headers, footers, comments, or tracked changes fully merged?", answer: "No. The current browser merger focuses on main document content, styles, numbering, hyperlinks, and embedded images; complex section-specific parts may be rejected or remain tied to the first document." },
    ],
    featured: false,
  },
  {
    id: "DOC-08",
    slug: "compress-docx",
    category: "word",
    title: "Compress DOCX",
    description: "Reduce DOCX size by recompressing supported embedded JPEG images and optimizing the package.",
    processor: "document",
    input: { formats: ["DOCX"], extensions: ["docx"], mimes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
    output: { formats: ["DOCX"], suffix: "compressed" },
    batch: false,
    action: "Compress DOCX",
    keywords: ["shrink", "optimize", "word", "document", "images"],
    searchTerms: ["compress docx", "reduce word document size", "make docx smaller"],
    metaDescription: "Compress a DOCX by recompressing supported embedded JPEG images with Light, Balanced, or Strong presets while keeping the file editable.",
    seoCopy: "Reduce a DOCX package locally when it contains recompressible JPEG media. Choose Light, Balanced, or Strong image quality; the result is offered only when the package becomes meaningfully smaller and remains a valid editable DOCX.",
    faqs: [
      { question: "What does Compress DOCX optimize?", answer: "It recompresses supported embedded JPEG images and applies safe ZIP package compression. It does not rasterize document text or rewrite all media formats." },
      { question: "Do the presets change image quality?", answer: "Yes. Light, Balanced, and Strong choose different JPEG quality targets. The route keeps an image replacement only when it is smaller." },
      { question: "What if the DOCX cannot be reduced usefully?", answer: "The route reports that no useful reduction was found instead of offering a misleading or needlessly degraded result." },
      { question: "Does compression remove editability?", answer: "No. The output remains a DOCX package; supported JPEG media is recompressed without flattening document text or structure." },
    ],
    featured: false,
  },
  {
    id: "DOC-09",
    slug: "extract-images-from-docx",
    category: "word",
    title: "Extract Images from DOCX",
    description: "Extract embedded image files from a DOCX without transcoding their original bytes.",
    processor: "document",
    input: { formats: ["DOCX"], extensions: ["docx"], mimes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
    output: { formats: ["Images", "ZIP"], suffix: "images" },
    batch: false,
    action: "Extract images",
    keywords: ["extract", "images", "media", "word", "download"],
    searchTerms: ["extract images from docx", "get pictures from word document", "save images from docx"],
    metaDescription: "Extract embedded images from a DOCX and download each original image or one ZIP archive. Shapes, charts, and icons are not claimed as images.",
    seoCopy: "Inspect a DOCX ZIP package and extract embedded media files without unnecessary transcoding. Preview supported raster results, see filename/type/size, download individual images, or download all results as a ZIP.",
    faqs: [
      { question: "Are image bytes transcoded?", answer: "No. Embedded media bytes are copied out of the DOCX package when the format is present as a package file." },
      { question: "Does this extract charts and shapes?", answer: "No. The route extracts normal embedded media files; vector shapes, charts, icons, and other drawing objects may not be separate image files." },
      { question: "Can I download all extracted images together?", answer: "Yes. When images are found, the route creates a ZIP containing the individual extracted files." },
      { question: "What happens when a DOCX has no embedded images?", answer: "The route shows an empty-result error and explains that non-image drawing objects are not extracted." },
    ],
    featured: false,
  },
  {
    id: "DOC-10",
    slug: "docx-metadata-cleaner",
    category: "word",
    title: "DOCX Metadata Cleaner",
    description: "Detect and remove supported core, application, and custom DOCX properties while keeping the document editable.",
    processor: "document",
    input: { formats: ["DOCX"], extensions: ["docx"], mimes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"] },
    output: { formats: ["DOCX"], suffix: "cleaned" },
    batch: false,
    action: "Clean metadata",
    keywords: ["metadata", "privacy", "author", "properties", "word"],
    searchTerms: ["remove metadata from docx", "clean word document properties", "docx metadata remover"],
    metaDescription: "Remove detected DOCX author, title, application, company, manager, revision, and custom properties locally while keeping the document editable.",
    seoCopy: "Inspect supported DOCX property parts before processing, show what can be removed, and create a cleaned editable DOCX. This route does not claim to remove comments, tracked changes, hidden text, thumbnails, or metadata embedded inside media.",
    faqs: [
      { question: "Which metadata does the cleaner remove?", answer: "It removes detected supported core properties such as author, title, subject, keywords, dates, and revision, plus supported application, company, manager, version, and custom document properties." },
      { question: "Does it remove all hidden data from a Word file?", answer: "No. Comments, tracked changes, hidden text, thumbnails, embedded media metadata, and every possible application-specific artifact are outside the supported cleaning scope." },
      { question: "What happens when no supported properties are present?", answer: "The route reports that no supported document properties were found instead of changing the file unnecessarily." },
      { question: "Is the cleaned file still editable?", answer: "Yes. The output is validated as a DOCX archive and the document body is not flattened." },
    ],
    featured: false,
  },
  {
    id: "AUD-01",
    slug: "trim-audio",
    category: "audio",
    title: "Trim Audio",
    description: "Keep only the part of an audio file you need.",
    processor: "media",
    input: { formats: ["MP3", "WAV", "M4A (AAC)", "AAC", "FLAC", "OGG (Vorbis)"], extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"], mimes: ["audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"] },
    output: { formats: ["MP3", "WAV", "M4A", "FLAC", "OGG"], suffix: "trimmed" },
    batch: false,
    action: "Trim audio",
    keywords: ["cut", "clip", "shorten", "sound"],
    featured: true,
  },
  {
    id: "AUD-02",
    slug: "audio-converter",
    category: "audio",
    title: "Audio Converter",
    description: "Convert between common audio formats with understandable quality choices.",
    processor: "media",
    input: { formats: ["MP3", "WAV", "M4A (AAC)", "AAC", "FLAC", "OGG (Vorbis)"], extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"], mimes: ["audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"] },
    output: { formats: ["MP3", "WAV", "M4A", "FLAC", "OGG"], suffix: "converted" },
    batch: true,
    action: "Convert audio",
    keywords: ["format", "change", "sound", "export"],
    featured: false,
  },
  {
    id: "AUD-03",
    slug: "merge-audio",
    category: "audio",
    title: "Merge Audio",
    description: "Put multiple audio files in order and make one continuous track.",
    processor: "media",
    input: { formats: ["MP3", "WAV", "M4A (AAC)", "AAC", "FLAC", "OGG (Vorbis)", "2+ files"], extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"], mimes: ["audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"] },
    output: { formats: ["MP3", "WAV", "M4A", "FLAC", "OGG"], suffix: "merged" },
    batch: true,
    minimumFiles: 2,
    action: "Merge audio",
    keywords: ["combine", "join", "tracks", "sound"],
    featured: false,
  },
  {
    id: "AUD-04",
    slug: "compress-audio",
    category: "audio",
    title: "Compress Audio",
    description: "Reduce audio bitrate and file size with quality presets.",
    processor: "media",
    input: { formats: ["MP3", "WAV", "M4A (AAC)", "AAC", "FLAC", "OGG (Vorbis)"], extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"], mimes: ["audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"] },
    output: { formats: ["MP3", "M4A"], suffix: "compressed" },
    batch: true,
    action: "Compress audio",
    keywords: ["shrink", "bitrate", "smaller", "sound"],
    featured: false,
  },
  {
    id: "VID-01",
    slug: "compress-video",
    category: "video",
    title: "Compress Video",
    description: "Reduce video size with simple quality presets while keeping dimensions and supported audio.",
    processor: "server",
    processingBoundary: "server",
    input: { formats: ["MP4 or MOV · H.264 or MPEG-4 Part 2 · AAC audio optional"], extensions: ["mp4", "mov"], mimes: ["video/mp4", "video/quicktime"] },
    output: { formats: ["WebM · VP9", "Opus audio optional"], suffix: "compressed" },
    batch: false,
    action: "Compress video",
    keywords: ["shrink", "optimize", "smaller", "size", "webm", "vp9"],
    featured: false,
    serverDisclosure: "This file is temporarily uploaded only to create the compressed result, then the temporary data is deleted automatically when the job completes or expires.",
  },
  {
    id: "VID-02",
    slug: "trim-video",
    category: "video",
    title: "Trim Video",
    description: "Trim verified H.264 video at keyframe-aligned starts locally without re-encoding.",
    processor: "media",
    input: { formats: ["MP4 · H.264", "MOV · H.264", "AAC audio optional"], extensions: ["mp4", "mov"], mimes: ["video/mp4", "video/quicktime"] },
    output: { formats: ["MP4"], suffix: "trimmed" },
    batch: false,
    action: "Trim video",
    keywords: ["cut", "clip", "shorten", "timeline"],
    featured: false,
    availability: "production-ready",
  },
  {
    id: "VID-03",
    slug: "video-to-mp3",
    category: "video",
    title: "Video to MP3",
    description: "Extract MP3 audio from verified H.264 video files with AAC sound.",
    processor: "media",
    input: { formats: ["MP4 · H.264 + AAC", "MOV · H.264 + AAC"], extensions: ["mp4", "mov"], mimes: ["video/mp4", "video/quicktime"] },
    output: { formats: ["MP3"], suffix: "audio" },
    batch: false,
    action: "Extract MP3",
    keywords: ["extract", "audio", "sound", "video"],
    featured: false,
    availability: "production-ready",
  },
  {
    id: "VID-04",
    slug: "mov-to-mp4",
    category: "video",
    title: "MOV to MP4",
    description: "Remux compatible H.264 MOV files into broadly compatible MP4 without re-encoding.",
    processor: "media",
    input: { formats: ["MOV · H.264 video", "AAC audio optional"], extensions: ["mov"], mimes: ["video/quicktime"] },
    output: { formats: ["MP4"], suffix: "mp4" },
    batch: false,
    action: "Convert to MP4",
    keywords: ["quicktime", "compatibility", "iphone", "convert"],
    featured: false,
    availability: "production-ready",
  },
  {
    id: "VID-05",
    slug: "video-converter",
    category: "video",
    title: "Video Converter",
    description: "Remux verified H.264 video between MP4 and MOV without re-encoding the streams.",
    processor: "media",
    input: { formats: ["MP4 · H.264", "MOV · H.264", "AAC audio optional"], extensions: ["mp4", "mov"], mimes: ["video/mp4", "video/quicktime"] },
    output: { formats: ["MP4", "MOV"], suffix: "converted" },
    batch: false,
    action: "Convert video",
    keywords: ["format", "change", "export", "media"],
    featured: false,
    availability: "production-ready",
  },
];

const searchStopWords = new Set(["to", "from", "for", "the", "a", "an", "of", "and", "into", "as", "by", "with"]);

export const getTool = (slug: string) => tools.find((tool) => tool.slug === slug);

export const getToolAvailability = (tool: Pick<ToolDefinition, "availability">): ToolAvailability => tool.availability ?? "production-ready";

export const getProcessingBoundary = (tool: Pick<ToolDefinition, "processingBoundary">): ProcessingBoundary => tool.processingBoundary ?? "browser";

export const isProductionReady = (tool: Pick<ToolDefinition, "availability">) => getToolAvailability(tool) === "production-ready";

export const getProductionReadyTools = () => tools.filter(isProductionReady);

export const getProductionReadyToolsByCategory = (category: ToolCategory) => getProductionReadyTools().filter((tool) => tool.category === category);

export const getProductionReadyTool = (slug: string) => tools.find((tool) => tool.slug === slug && isProductionReady(tool));

export const getToolsByCategory = (category: ToolCategory) => tools.filter((tool) => tool.category === category);

export const getToolPath = (tool: Pick<ToolDefinition, "category" | "slug">) => `/${tool.category}/${tool.slug}/`;

export const normalizeSearchText = (value: string) => String(value)
  .toLowerCase()
  .replace(/\bjpeg(s)?\b/g, "jpg")
  .replace(/\bimages?\b/g, "image")
  .replace(/\bphotos?\b/g, "image")
  .replace(/\bpictures?\b/g, "image")
  .replace(/\bconversions?\b/g, "convert")
  .replace(/\bconverters?\b/g, "converter")
  .replace(/[^a-z0-9]+/g, " ")
  .trim();

const getSearchTokens = (value: string) => normalizeSearchText(value)
  .split(/\s+/)
  .filter((token) => token && !searchStopWords.has(token));

const getToolSearchText = (tool: ToolDefinition) => normalizeSearchText([
  tool.title,
  tool.description,
  tool.category,
  tool.input.formats.join(" "),
  tool.keywords.join(" "),
  ...(tool.searchTerms ?? []),
].join(" "));

const getToolSearchScore = (tool: ToolDefinition, query: string) => {
  const normalizedQuery = normalizeSearchText(query);
  if (!normalizedQuery) return 1;

  const title = normalizeSearchText(tool.title);
  const searchTerms = normalizeSearchText((tool.searchTerms ?? []).join(" "));
  const haystack = getToolSearchText(tool);
  const tokens = getSearchTokens(query);
  if (!tokens.length || !tokens.every((token) => haystack.includes(token))) return 0;

  let score = 1;
  if (title === normalizedQuery) score += 1000;
  if (title.includes(normalizedQuery)) score += 500;
  if (searchTerms.includes(normalizedQuery)) score += 400;
  tokens.forEach((token) => {
    if (title.includes(token)) score += 80;
    if (searchTerms.includes(token)) score += 30;
  });
  return score;
};

export const findMatchingTools = (query: string) => {
  const normalizedQuery = normalizeSearchText(query);
  const publicTools = getProductionReadyTools();
  if (!normalizedQuery) return publicTools;

  const exactMatches = publicTools.filter((tool) => normalizeSearchText(tool.title) === normalizedQuery
    || (tool.searchTerms ?? []).some((term) => normalizeSearchText(term) === normalizedQuery));
  if (exactMatches.length) return exactMatches;

  return publicTools
    .map((tool) => ({ tool, score: getToolSearchScore(tool, query) }))
    .filter(({ score }) => score > 0)
    .sort((left, right) => right.score - left.score || left.tool.title.localeCompare(right.tool.title))
    .map(({ tool }) => tool);
};

export const toolMatches = (tool: ToolDefinition, query: string) => getToolSearchScore(tool, query) > 0;
