import type { CategoryDefinition, ProcessingBoundary, ToolCategory, ToolAvailability, ToolDefinition } from "./types";

export const categoryMeta: Record<ToolCategory, CategoryDefinition> = {
  image: {
    label: "Image",
    number: "01",
    description: "Make everyday image fixes without opening a heavy editor.",
    visualFormat: "PNG",
    visualName: "photo.png",
    visualSize: "3.8 MB",
    groups: [
      { key: "optimize", label: "Optimize", description: "Reduce image encoding size while keeping dimensions by default.", toolSlugs: ["compress-image"] },
      { key: "resize-crop", label: "Resize & crop", description: "Change pixel dimensions or frame an image to a useful ratio.", toolSlugs: ["resize-image", "crop-image"] },
      { key: "format-conversion", label: "Format conversion", description: "Move between supported JPG, PNG, WebP, and HEIC/HEIF image formats.", toolSlugs: ["png-to-jpg", "jpg-to-png", "jpg-to-webp", "png-to-webp", "webp-to-jpg", "webp-to-png", "heic-to-jpg"] },
    ],
    content: {
      heading: "Practical fixes for everyday raster images.",
      body: "Resize, compress, crop, or change the format of supported raster images without opening a full editor.",
      formats: "JPG/JPEG, PNG, WebP, and supported HEIC/HEIF input for HEIC to JPG.",
      intents: "Reduce file size, change dimensions, crop to a useful frame, or make an image compatible with another app or service.",
      processing: "Image routes run in the browser on your device; no image bytes are sent to a server.",
    },
  },
  pdf: {
    label: "PDF & Document",
    number: "02",
    description: "Organize pages and turn documents into useful, shareable files.",
    visualFormat: "PDF",
    visualName: "report.pdf",
    visualSize: "12 pages",
    groups: [
      { key: "combine-organize", label: "Combine & organize", description: "Join documents or change page order and membership.", toolSlugs: ["merge-pdf", "organize-pdf"] },
      { key: "edit-pages", label: "Edit pages", description: "Extract ranges, rotate pages, or add a visible overlay.", toolSlugs: ["split-pdf", "rotate-pdf", "watermark-pdf"] },
      { key: "convert", label: "Convert", description: "Create PDFs from images or render PDF pages as JPG files.", toolSlugs: ["jpg-to-pdf", "png-to-pdf", "webp-to-pdf", "pdf-to-jpg"] },
      { key: "compress", label: "Compress", description: "Reduce PDF size through the disclosed temporary compression workflow.", toolSlugs: ["compress-pdf"] },
    ],
    content: {
      heading: "Page and document workflows in one place.",
      body: "Work with PDF pages, create PDFs from images, render pages as JPGs, or add a visible watermark.",
      formats: "PDF, JPG/JPEG, PNG, and WebP depending on the selected workflow.",
      intents: "Combine, split, reorder, duplicate, rotate, watermark, compress, or convert document pages.",
      processing: "PDF operations run locally except Compress PDF, which uses a disclosed temporary server job and automatic deletion.",
    },
  },
  audio: {
    label: "Audio",
    number: "03",
    description: "Trim, merge, and convert audio with clear controls and useful defaults.",
    visualFormat: "MP3",
    visualName: "interview.mp3",
    visualSize: "8.4 MB",
    groups: [
      { key: "edit", label: "Edit", description: "Trim a time range or join multiple tracks into one.", toolSlugs: ["trim-audio", "merge-audio"] },
      { key: "convert", label: "Convert", description: "Move between the verified common audio formats.", toolSlugs: ["audio-converter"] },
      { key: "compress", label: "Compress", description: "Reduce bitrate and file size with understandable presets.", toolSlugs: ["compress-audio"] },
    ],
    content: {
      heading: "Clear controls for common audio edits.",
      body: "Trim a section, join tracks, change a supported format, or reduce bitrate with understandable quality presets.",
      formats: "MP3, WAV, M4A/AAC, FLAC, and OGG/Vorbis within the verified audio matrix.",
      intents: "Cut a clip, make one continuous track, export another audio format, or make a file smaller.",
      processing: "Audio routes use the approved browser runtime and keep selected files on the device.",
    },
  },
  video: {
    label: "Video",
    number: "04",
    description: "Extract audio and remux verified MOV files without changing the original video streams.",
    visualFormat: "MP4",
    visualName: "clip.mp4",
    visualSize: "84 MB",
    groups: [
      { key: "edit", label: "Edit", description: "Keep a keyframe-aligned section of verified video.", toolSlugs: ["trim-video"] },
      { key: "convert", label: "Convert", description: "Extract audio or remux supported MP4 and MOV containers.", toolSlugs: ["video-to-mp3", "mov-to-mp4", "video-converter"] },
      { key: "compress", label: "Compress", description: "Use the disclosed temporary workflow to create a smaller WebM result.", toolSlugs: ["compress-video"] },
    ],
    content: {
      heading: "Focused video workflows for verified files.",
      body: "Trim supported H.264 video, extract MP3 audio, remux MOV and MP4 containers, or use the disclosed compression route.",
      formats: "MP4 and QuickTime MOV with the route-specific H.264/AAC support matrix.",
      intents: "Cut a keyframe-aligned clip, get audio from a video, make MOV compatible with MP4, or change a supported container.",
      processing: "Trim, extraction, and remux routes run locally; Compress Video uses a disclosed temporary server job and automatic deletion.",
    },
  },
};

export const tools: ToolDefinition[] = [
  {
    id: "IMG-01",
    slug: "compress-image",
    category: "image",
    title: "Compress Image",
    description: "Reduce image size while keeping the dimensions you need.",
    processor: "image",
    input: { formats: ["JPG", "PNG", "WebP"], extensions: ["jpg", "jpeg", "png", "webp"], mimes: ["image/jpeg", "image/png", "image/webp"] },
    output: { formats: ["JPG", "PNG", "WebP"], suffix: "optimized" },
    batch: true,
    action: "Compress image",
    keywords: ["shrink", "optimize", "smaller", "quality"],
    featured: true,
  },
  {
    id: "IMG-02",
    slug: "resize-image",
    category: "image",
    title: "Resize Image",
    description: "Scale images by percentage while keeping the original safe.",
    processor: "image",
    input: { formats: ["JPG", "PNG", "WebP"], extensions: ["jpg", "jpeg", "png", "webp"], mimes: ["image/jpeg", "image/png", "image/webp"] },
    output: { formats: ["JPG", "PNG", "WebP"], suffix: "resized" },
    batch: true,
    action: "Resize image",
    keywords: ["dimensions", "pixels", "scale", "smaller", "larger"],
    featured: true,
  },
  {
    id: "IMG-03",
    slug: "crop-image",
    category: "image",
    title: "Crop Image",
    description: "Select a freeform or common-ratio crop area, preview it, and export a clean raster image.",
    processor: "image",
    input: { formats: ["JPG", "PNG", "WebP"], extensions: ["jpg", "jpeg", "png", "webp"], mimes: ["image/jpeg", "image/png", "image/webp"] },
    output: { formats: ["JPG", "PNG", "WebP"], suffix: "cropped" },
    batch: false,
    action: "Crop image",
    keywords: ["trim", "frame", "aspect ratio", "square"],
    featured: false,
  },
  {
    id: "IMG-05",
    slug: "png-to-jpg",
    category: "image",
    title: "PNG to JPG",
    description: "Convert PNG images to JPG and choose a background for transparent pixels.",
    processor: "image",
    input: { formats: ["PNG"], extensions: ["png"], mimes: ["image/png"] },
    output: { formats: ["JPG"], suffix: "jpg" },
    batch: true,
    action: "Convert to JPG",
    keywords: ["transparent", "background", "jpeg", "convert"],
    searchTerms: ["png to jpeg", "png image to jpg"],
    metaDescription: "Convert PNG images to JPG with a chosen background for transparent pixels. Process files locally with DoMyFile.",
    seoCopy: "Convert PNG images to fixed-output JPG files in your browser. Transparent pixels use a white background by default, and you can choose another color before processing.",
    faqs: [
      { question: "What does PNG to JPG accept?", answer: "This route accepts PNG images only and rejects other image formats before processing." },
      { question: "What happens to transparent pixels?", answer: "JPG does not support transparency, so transparent pixels use the selected background color. White is the default." },
      { question: "What will I download?", answer: "Every successful result is a JPG file with the original image dimensions." },
    ],
    featured: true,
  },
  {
    id: "IMG-06",
    slug: "jpg-to-png",
    category: "image",
    title: "JPG to PNG",
    description: "Convert JPG images to PNG while preserving their original dimensions.",
    processor: "image",
    input: { formats: ["JPG"], extensions: ["jpg", "jpeg"], mimes: ["image/jpeg"] },
    output: { formats: ["PNG"], suffix: "png" },
    batch: true,
    action: "Convert to PNG",
    keywords: ["convert", "jpeg", "lossless", "image"],
    searchTerms: ["jpg to jpeg", "jpeg to png", "jpg image to png"],
    metaDescription: "Convert JPG images to PNG while keeping their dimensions. DoMyFile processes JPG files locally in your browser.",
    seoCopy: "Convert JPG images to fixed-output PNG files without changing their decoded dimensions. Select one or more JPG files and download the PNG results locally.",
    faqs: [
      { question: "What does JPG to PNG accept?", answer: "This route accepts JPG and JPEG images only. PNG, WebP, and other files are rejected before conversion." },
      { question: "Will the dimensions change?", answer: "No. The shared Image Engine preserves the decoded width and height for JPG to PNG conversion." },
      { question: "What will I download?", answer: "Every successful result is a PNG file." },
    ],
    featured: false,
  },
  {
    id: "IMG-07",
    slug: "jpg-to-webp",
    category: "image",
    title: "JPG to WebP",
    description: "Convert JPG images to compact WebP files for modern websites and apps.",
    processor: "image",
    input: { formats: ["JPG"], extensions: ["jpg", "jpeg"], mimes: ["image/jpeg"] },
    output: { formats: ["WebP"], suffix: "webp" },
    batch: true,
    action: "Convert to WebP",
    keywords: ["jpeg", "modern", "website", "smaller", "image"],
    searchTerms: ["jpg image to webp", "jpeg to webp"],
    metaDescription: "Convert JPG images to WebP for modern websites and apps. Choose files and create WebP results locally with DoMyFile.",
    seoCopy: "Convert JPG images to fixed-output WebP files with the shared Image Engine. The conversion runs locally and keeps the original dimensions.",
    faqs: [
      { question: "What does JPG to WebP accept?", answer: "This route accepts JPG and JPEG images only." },
      { question: "What format is the result?", answer: "Every successful result is WebP. There is no output-format selector on this focused route." },
      { question: "Can I convert multiple JPG files?", answer: "Yes. JPG to WebP keeps the existing batch workflow, so you can select multiple JPG files in one job." },
    ],
    featured: true,
  },
  {
    id: "IMG-09",
    slug: "png-to-webp",
    category: "image",
    title: "PNG to WebP",
    description: "Convert PNG images to WebP for a smaller, web-ready image.",
    processor: "image",
    input: { formats: ["PNG"], extensions: ["png"], mimes: ["image/png"] },
    output: { formats: ["WebP"], suffix: "webp" },
    batch: true,
    action: "Convert to WebP",
    keywords: ["modern", "website", "smaller", "image", "transparent"],
    searchTerms: ["png image to webp"],
    metaDescription: "Convert PNG images to WebP for web-ready files with smaller sizes. DoMyFile keeps this batch workflow in your browser.",
    seoCopy: "Convert PNG images to fixed-output WebP files while keeping the decoded dimensions. Select one or more PNG images and download the web-ready results.",
    faqs: [
      { question: "What does PNG to WebP accept?", answer: "This route accepts PNG images only." },
      { question: "What format is the result?", answer: "Every successful result is WebP. The output format is fixed to keep the workflow focused." },
      { question: "Does the route support batches?", answer: "Yes. You can select multiple PNG files and receive one WebP result for each successful input." },
    ],
    featured: false,
  },
  {
    id: "IMG-10",
    slug: "webp-to-jpg",
    category: "image",
    title: "WebP to JPG",
    description: "Convert WebP images to broadly compatible JPG files.",
    processor: "image",
    input: { formats: ["WebP"], extensions: ["webp"], mimes: ["image/webp"] },
    output: { formats: ["JPG"], suffix: "jpg" },
    batch: true,
    action: "Convert to JPG",
    keywords: ["compatibility", "jpeg", "image", "convert"],
    searchTerms: ["webp image to jpg", "webp to jpeg"],
    metaDescription: "Convert WebP images to compatible JPG files with DoMyFile. Select WebP images and process them locally in your browser.",
    seoCopy: "Convert WebP images to fixed-output JPG files for apps and services that need broad JPEG compatibility. The shared Image Engine processes each file locally.",
    faqs: [
      { question: "What does WebP to JPG accept?", answer: "This route accepts WebP images only." },
      { question: "What happens to transparency?", answer: "JPG does not support transparency, so transparent pixels use a white background." },
      { question: "Can I convert multiple WebP files?", answer: "Yes. Batch conversion is supported, with one JPG result per successful WebP input." },
    ],
    featured: false,
  },
  {
    id: "IMG-11",
    slug: "webp-to-png",
    category: "image",
    title: "WebP to PNG",
    description: "Convert WebP images to PNG while keeping their original dimensions.",
    processor: "image",
    input: { formats: ["WebP"], extensions: ["webp"], mimes: ["image/webp"] },
    output: { formats: ["PNG"], suffix: "png" },
    batch: true,
    action: "Convert to PNG",
    keywords: ["lossless", "transparent", "image", "convert"],
    searchTerms: ["webp image to png"],
    metaDescription: "Convert WebP images to PNG while preserving dimensions. DoMyFile processes WebP files locally and fixes the output to PNG.",
    seoCopy: "Convert WebP images to fixed-output PNG files without changing their decoded dimensions. Select one or more WebP files for a local batch conversion.",
    faqs: [
      { question: "What does WebP to PNG accept?", answer: "This route accepts WebP images only." },
      { question: "Will the dimensions change?", answer: "No. The shared Image Engine preserves the decoded width and height for WebP to PNG conversion." },
      { question: "What format is the result?", answer: "Every successful result is PNG, with no output-format dropdown." },
    ],
    featured: false,
  },
  {
    id: "IMG-08",
    slug: "heic-to-jpg",
    category: "image",
    title: "HEIC to JPG",
    description: "Prepare supported HEIC or HEIF images for broader compatibility.",
    processor: "image",
    input: { formats: ["HEIC", "HEIF"], extensions: ["heic", "heif"], mimes: ["image/heic", "image/heif"] },
    output: { formats: ["JPG"], suffix: "jpg" },
    batch: true,
    action: "Convert to JPG",
    keywords: ["iphone", "apple", "photo", "compatibility"],
    featured: false,
  },
  {
    id: "PDF-01",
    slug: "compress-pdf",
    category: "pdf",
    title: "Compress PDF",
    description: "Reduce PDF size while preserving selectable text, vector content, and page structure where possible.",
    processor: "server",
    processingBoundary: "server",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "compressed" },
    batch: false,
    action: "Compress PDF",
    keywords: ["shrink", "optimize", "document", "smaller"],
    featured: false,
    serverDisclosure: "This file is temporarily uploaded only to create the compressed result, then the temporary data is deleted automatically when the job completes or expires.",
  },
  {
    id: "PDF-02",
    slug: "merge-pdf",
    category: "pdf",
    title: "Merge PDF",
    description: "Combine two or more PDFs and keep their page order under control.",
    processor: "pdf",
    input: { formats: ["PDF", "2+ files"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "merged" },
    batch: true,
    minimumFiles: 2,
    action: "Merge PDFs",
    keywords: ["combine", "join", "documents", "pages"],
    featured: true,
  },
  {
    id: "PDF-03",
    slug: "split-pdf",
    category: "pdf",
    title: "Split PDF",
    description: "Turn selected pages or ranges into separate PDF files.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "split" },
    batch: false,
    action: "Split PDF",
    keywords: ["separate", "pages", "extract", "range"],
    featured: false,
  },
  {
    id: "PDF-09",
    slug: "jpg-to-pdf",
    category: "pdf",
    title: "JPG to PDF",
    description: "Turn one or more JPG images into a clean PDF with page controls.",
    processor: "pdf",
    input: { formats: ["JPG"], extensions: ["jpg", "jpeg"], mimes: ["image/jpeg"] },
    output: { formats: ["PDF"], suffix: "pdf" },
    batch: true,
    action: "Convert to PDF",
    keywords: ["photo", "document", "pages", "convert", "create"],
    searchTerms: ["jpg image to pdf", "jpeg to pdf", "photo jpg to pdf"],
    metaDescription: "Convert one or more JPG images to PDF with page size, orientation, and order controls. Process files locally with DoMyFile.",
    seoCopy: "Turn JPG images into a fixed-output PDF directly in your browser. Add multiple JPG files, arrange their page order, and choose a page size or orientation.",
    faqs: [
      { question: "What does JPG to PDF accept?", answer: "This route accepts JPG and JPEG images only." },
      { question: "Can I add multiple JPG images?", answer: "Yes. Batch support is preserved, and each selected JPG becomes one PDF page in the chosen order." },
      { question: "What format is the result?", answer: "Every successful job creates a PDF. Page size and orientation are configurable, but the output format is fixed." },
    ],
    featured: true,
  },
  {
    id: "PDF-10",
    slug: "png-to-pdf",
    category: "pdf",
    title: "PNG to PDF",
    description: "Turn one or more PNG images into a clean PDF with page controls.",
    processor: "pdf",
    input: { formats: ["PNG"], extensions: ["png"], mimes: ["image/png"] },
    output: { formats: ["PDF"], suffix: "pdf" },
    batch: true,
    action: "Convert to PDF",
    keywords: ["image", "document", "pages", "convert", "create"],
    searchTerms: ["png image to pdf"],
    metaDescription: "Convert one or more PNG images to PDF with page size, orientation, and order controls. DoMyFile processes PNG files locally.",
    seoCopy: "Turn PNG images into a fixed-output PDF in your browser. Select one or more PNG files, review their page order, and use the available page controls.",
    faqs: [
      { question: "What does PNG to PDF accept?", answer: "This route accepts PNG images only." },
      { question: "Can I convert a batch of PNG files?", answer: "Yes. Each selected PNG becomes one PDF page, and you can reorder the pages before creating the PDF." },
      { question: "What format is the result?", answer: "Every successful job creates a PDF. The output format is fixed to PDF." },
    ],
    featured: false,
  },
  {
    id: "PDF-11",
    slug: "webp-to-pdf",
    category: "pdf",
    title: "WebP to PDF",
    description: "Turn one or more WebP images into a clean PDF with page controls.",
    processor: "pdf",
    input: { formats: ["WebP"], extensions: ["webp"], mimes: ["image/webp"] },
    output: { formats: ["PDF"], suffix: "pdf" },
    batch: true,
    action: "Convert to PDF",
    keywords: ["image", "document", "pages", "convert", "create", "web"],
    searchTerms: ["webp image to pdf"],
    metaDescription: "Convert one or more WebP images to PDF with page size, orientation, and order controls. DoMyFile keeps the workflow local.",
    seoCopy: "Turn WebP images into a fixed-output PDF in your browser. Add multiple WebP files, review the page order, and choose the page layout before download.",
    faqs: [
      { question: "What does WebP to PDF accept?", answer: "This route accepts WebP images only." },
      { question: "Can I add multiple WebP images?", answer: "Yes. Batch support is preserved, with one PDF page for each successful WebP input." },
      { question: "What format is the result?", answer: "Every successful job creates a PDF. Page layout is configurable, but the output format is fixed." },
    ],
    featured: false,
  },
  {
    id: "PDF-05",
    slug: "pdf-to-jpg",
    category: "pdf",
    title: "PDF to JPG",
    description: "Export selected PDF pages as broadly compatible JPG images.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["JPG"], suffix: "jpg" },
    batch: false,
    action: "Convert to JPG",
    keywords: ["render", "pages", "image", "export"],
    featured: false,
  },
  {
    id: "PDF-06",
    slug: "organize-pdf",
    category: "pdf",
    title: "Organize PDF",
    description: "Reorder, duplicate, or remove pages in one focused workspace.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "organized" },
    batch: false,
    action: "Organize PDF",
    keywords: ["reorder", "duplicate", "delete", "pages"],
    featured: false,
  },
  {
    id: "PDF-07",
    slug: "rotate-pdf",
    category: "pdf",
    title: "Rotate PDF",
    description: "Rotate selected pages or the whole document by right angles.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "rotated" },
    batch: false,
    action: "Rotate PDF",
    keywords: ["turn", "landscape", "portrait", "pages"],
    featured: false,
  },
  {
    id: "PDF-08",
    slug: "watermark-pdf",
    category: "pdf",
    title: "Watermark PDF",
    description: "Add a visible text or image watermark with simple placement controls.",
    processor: "pdf",
    input: { formats: ["PDF"], extensions: ["pdf"], mimes: ["application/pdf"] },
    output: { formats: ["PDF"], suffix: "watermarked" },
    batch: false,
    action: "Watermark PDF",
    keywords: ["stamp", "protect", "label", "overlay"],
    featured: false,
  },
  {
    id: "AUD-01",
    slug: "trim-audio",
    category: "audio",
    title: "Trim Audio",
    description: "Keep only the part of an audio file you need.",
    processor: "media",
    input: { formats: ["MP3", "WAV", "M4A (AAC)", "AAC", "FLAC", "OGG (Vorbis)"], extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"], mimes: ["audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"] },
    output: { formats: ["MP3", "WAV", "M4A", "FLAC", "OGG"], suffix: "trimmed" },
    batch: false,
    action: "Trim audio",
    keywords: ["cut", "clip", "shorten", "sound"],
    featured: true,
  },
  {
    id: "AUD-02",
    slug: "audio-converter",
    category: "audio",
    title: "Audio Converter",
    description: "Convert between common audio formats with understandable quality choices.",
    processor: "media",
    input: { formats: ["MP3", "WAV", "M4A (AAC)", "AAC", "FLAC", "OGG (Vorbis)"], extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"], mimes: ["audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"] },
    output: { formats: ["MP3", "WAV", "M4A", "FLAC", "OGG"], suffix: "converted" },
    batch: true,
    action: "Convert audio",
    keywords: ["format", "change", "sound", "export"],
    featured: false,
  },
  {
    id: "AUD-03",
    slug: "merge-audio",
    category: "audio",
    title: "Merge Audio",
    description: "Put multiple audio files in order and make one continuous track.",
    processor: "media",
    input: { formats: ["MP3", "WAV", "M4A (AAC)", "AAC", "FLAC", "OGG (Vorbis)", "2+ files"], extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"], mimes: ["audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"] },
    output: { formats: ["MP3", "WAV", "M4A", "FLAC", "OGG"], suffix: "merged" },
    batch: true,
    minimumFiles: 2,
    action: "Merge audio",
    keywords: ["combine", "join", "tracks", "sound"],
    featured: false,
  },
  {
    id: "AUD-04",
    slug: "compress-audio",
    category: "audio",
    title: "Compress Audio",
    description: "Reduce audio bitrate and file size with quality presets.",
    processor: "media",
    input: { formats: ["MP3", "WAV", "M4A (AAC)", "AAC", "FLAC", "OGG (Vorbis)"], extensions: ["mp3", "wav", "m4a", "aac", "flac", "ogg"], mimes: ["audio/mpeg", "audio/wav", "audio/x-wav", "audio/mp4", "audio/aac", "audio/flac", "audio/ogg"] },
    output: { formats: ["MP3", "M4A"], suffix: "compressed" },
    batch: true,
    action: "Compress audio",
    keywords: ["shrink", "bitrate", "smaller", "sound"],
    featured: false,
  },
  {
    id: "VID-01",
    slug: "compress-video",
    category: "video",
    title: "Compress Video",
    description: "Reduce video size with simple quality presets while keeping dimensions and supported audio.",
    processor: "server",
    processingBoundary: "server",
    input: { formats: ["MP4 or MOV · H.264 or MPEG-4 Part 2 · AAC audio optional"], extensions: ["mp4", "mov"], mimes: ["video/mp4", "video/quicktime"] },
    output: { formats: ["WebM · VP9", "Opus audio optional"], suffix: "compressed" },
    batch: false,
    action: "Compress video",
    keywords: ["shrink", "optimize", "smaller", "size", "webm", "vp9"],
    featured: false,
    serverDisclosure: "This file is temporarily uploaded only to create the compressed result, then the temporary data is deleted automatically when the job completes or expires.",
  },
  {
    id: "VID-02",
    slug: "trim-video",
    category: "video",
    title: "Trim Video",
    description: "Trim verified H.264 video at keyframe-aligned starts locally without re-encoding.",
    processor: "media",
    input: { formats: ["MP4 · H.264", "MOV · H.264", "AAC audio optional"], extensions: ["mp4", "mov"], mimes: ["video/mp4", "video/quicktime"] },
    output: { formats: ["MP4"], suffix: "trimmed" },
    batch: false,
    action: "Trim video",
    keywords: ["cut", "clip", "shorten", "timeline"],
    featured: false,
    availability: "production-ready",
  },
  {
    id: "VID-03",
    slug: "video-to-mp3",
    category: "video",
    title: "Video to MP3",
    description: "Extract MP3 audio from verified H.264 video files with AAC sound.",
    processor: "media",
    input: { formats: ["MP4 · H.264 + AAC", "MOV · H.264 + AAC"], extensions: ["mp4", "mov"], mimes: ["video/mp4", "video/quicktime"] },
    output: { formats: ["MP3"], suffix: "audio" },
    batch: false,
    action: "Extract MP3",
    keywords: ["extract", "audio", "sound", "video"],
    featured: false,
    availability: "production-ready",
  },
  {
    id: "VID-04",
    slug: "mov-to-mp4",
    category: "video",
    title: "MOV to MP4",
    description: "Remux compatible H.264 MOV files into broadly compatible MP4 without re-encoding.",
    processor: "media",
    input: { formats: ["MOV · H.264 video", "AAC audio optional"], extensions: ["mov"], mimes: ["video/quicktime"] },
    output: { formats: ["MP4"], suffix: "mp4" },
    batch: false,
    action: "Convert to MP4",
    keywords: ["quicktime", "compatibility", "iphone", "convert"],
    featured: false,
    availability: "production-ready",
  },
  {
    id: "VID-05",
    slug: "video-converter",
    category: "video",
    title: "Video Converter",
    description: "Remux verified H.264 video between MP4 and MOV without re-encoding the streams.",
    processor: "media",
    input: { formats: ["MP4 · H.264", "MOV · H.264", "AAC audio optional"], extensions: ["mp4", "mov"], mimes: ["video/mp4", "video/quicktime"] },
    output: { formats: ["MP4", "MOV"], suffix: "converted" },
    batch: false,
    action: "Convert video",
    keywords: ["format", "change", "export", "media"],
    featured: false,
    availability: "production-ready",
  },
];

const searchStopWords = new Set(["to", "from", "for", "the", "a", "an", "of", "and", "into", "as", "by", "with"]);

export const getTool = (slug: string) => tools.find((tool) => tool.slug === slug);

export const getToolAvailability = (tool: Pick<ToolDefinition, "availability">): ToolAvailability => tool.availability ?? "production-ready";

export const getProcessingBoundary = (tool: Pick<ToolDefinition, "processingBoundary">): ProcessingBoundary => tool.processingBoundary ?? "browser";

export const isProductionReady = (tool: Pick<ToolDefinition, "availability">) => getToolAvailability(tool) === "production-ready";

export const getToolsByCategory = (category: ToolCategory) => tools.filter((tool) => tool.category === category);

export const getToolPath = (tool: Pick<ToolDefinition, "category" | "slug">) => `/${tool.category}/${tool.slug}/`;

export const normalizeSearchText = (value: string) => String(value)
  .toLowerCase()
  .replace(/\bjpeg(s)?\b/g, "jpg")
  .replace(/\bimages?\b/g, "image")
  .replace(/\bphotos?\b/g, "image")
  .replace(/\bpictures?\b/g, "image")
  .replace(/\bconversions?\b/g, "convert")
  .replace(/\bconverters?\b/g, "converter")
  .replace(/[^a-z0-9]+/g, " ")
  .trim();

const getSearchTokens = (value: string) => normalizeSearchText(value)
  .split(/\s+/)
  .filter((token) => token && !searchStopWords.has(token));

const getToolSearchText = (tool: ToolDefinition) => normalizeSearchText([
  tool.title,
  tool.description,
  tool.category,
  tool.input.formats.join(" "),
  tool.keywords.join(" "),
  ...(tool.searchTerms ?? []),
].join(" "));

const getToolSearchScore = (tool: ToolDefinition, query: string) => {
  const normalizedQuery = normalizeSearchText(query);
  if (!normalizedQuery) return 1;

  const title = normalizeSearchText(tool.title);
  const searchTerms = normalizeSearchText((tool.searchTerms ?? []).join(" "));
  const haystack = getToolSearchText(tool);
  const tokens = getSearchTokens(query);
  if (!tokens.length || !tokens.every((token) => haystack.includes(token))) return 0;

  let score = 1;
  if (title === normalizedQuery) score += 1000;
  if (title.includes(normalizedQuery)) score += 500;
  if (searchTerms.includes(normalizedQuery)) score += 400;
  tokens.forEach((token) => {
    if (title.includes(token)) score += 80;
    if (searchTerms.includes(token)) score += 30;
  });
  return score;
};

export const findMatchingTools = (query: string) => {
  const normalizedQuery = normalizeSearchText(query);
  if (!normalizedQuery) return tools;

  const exactMatches = tools.filter((tool) => normalizeSearchText(tool.title) === normalizedQuery
    || (tool.searchTerms ?? []).some((term) => normalizeSearchText(term) === normalizedQuery));
  if (exactMatches.length) return exactMatches;

  return tools
    .map((tool) => ({ tool, score: getToolSearchScore(tool, query) }))
    .filter(({ score }) => score > 0)
    .sort((left, right) => right.score - left.score || left.tool.title.localeCompare(right.tool.title))
    .map(({ tool }) => tool);
};

export const toolMatches = (tool: ToolDefinition, query: string) => getToolSearchScore(tool, query) > 0;
